package org.example.backend.moderation;

/**
 * Implemented by content documents that flow through the moderation pipeline
 * (Post, Comment, Forum). The accessors are generated by Lombok on the concrete
 * classes; this interface lets {@link ModerationVerdictConsumer} apply verdicts
 * generically without reflection.
 */
public interface Moderatable {

    ModerationStatus getModerationStatus();

    void setModerationStatus(ModerationStatus status);

    /**
     * Guard against stale verdicts: bumped on every edit that re-enqueues the text
     * for moderation. A verdict carrying an older version is discarded — the newer
     * request's verdict is authoritative. Legacy documents read as 0 (never matches
     * an enqueued version, which starts at 1).
     */
    long getModerationVersion();

    void setModerationVersion(long version);

    /** From {@code SoftDeletableDocument} — lets verdict application skip content already gone. */
    Boolean getIsDeleted();
}
